app_registration:
  path: /registration
  controller: App\Controller\RegistrationController::register

app_user_login:
  path: /user/login
  controller: App\Controller\UserLoginController::login







